# These are supported funding model platforms
number = 5 # тип данных int 
#создали пепеменную к которой в следующей строке обращаемся
print("результат:", number)
del number
#удаляет переменную 
number = 7 
#можем либо создать новую либо поменять значение в процессе кода, при этом значение до изменения остануться прежними
print("результат:", number)
w = 4.5 #тип данных float
abc = "результат:" #тип данных string
print(abc, w)
boo = True #либо False #тип данных bool 
print(boo)
#разные типы данных можно писать через , но нельзя через +